<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1552014668365" stop="1552014668447">
  <name>scripts.test_contact</name>
  <labels/>
  <test-cases>
    <test-case start="1552014668365" status="failed" stop="1552014668447">
      <name>TestAbc.test_abc1</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;scripts.test_contact.TestAbc object at 0x000001D65AB500B8&gt;

    def test_abc1(self):
&gt;       assert 0
E       assert 0

test_contact.py:9: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="10212-MainThread"/>
        <label name="host" value="MSI"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
